###
# The agent surface: make the `pluto-collab` CLI PRESENT and DISCOVERABLE so any terminal-based
# coding agent in a SpaceStation session "just works" — no MCP, no plugins, no skills.
#
#  1. ACCESS. `pluto-collab` is a tiny bundled shell script. `Pkg.Apps.add` installs only the
#     `spacestation` Julia entrypoint, so on startup we drop the script next to `spacestation` on PATH
#     (the apps bin dir, which the user already has on PATH to run `spacestation` at all).
#  2. CONNECTION. The integrated terminal exports PLUTOSPACE_PORT / PLUTOSPACE_SECRET /
#     PLUTOSPACE_WORKSPACE, so a tool targets THIS live server with zero discovery (and no
#     ambiguity when several servers run).
#  3. UNDERSTANDING (opt-in, PLUTOSPACE_AGENTS_MD=1). Drop a managed collab section into the
#     workspace's AGENTS.md and CLAUDE.md — the file conventions coding agents already read.
###

# The pluto-collab script, embedded at precompile so it ships even when installed purely as an app.
const _PLUTO_COLLAB_PATH = normpath(joinpath(@__DIR__, "..", "bin", "pluto-collab"))
isfile(_PLUTO_COLLAB_PATH) && include_dependency(_PLUTO_COLLAB_PATH)
const PLUTO_COLLAB_SCRIPT = isfile(_PLUTO_COLLAB_PATH) ? read(_PLUTO_COLLAB_PATH, String) : ""

"The directory where `Pkg.Apps` installs app launchers — the same dir that holds the `spacestation` executable, and which the user already has on PATH."
apps_bin_dir() = joinpath(first(DEPOT_PATH), "bin")

"""
    neutralize_app_load_path_pin!()

The `Pkg.Apps` launcher shim for `spacestation` exports

    JULIA_LOAD_PATH=<depot>/environments/apps/SpaceStation

so that `julia -m SpaceStation` boots the server with its *own* dependencies. That is correct for
booting us — but the variable is then inherited by every process the server spawns: notebook
workers (via Malt) and the integrated terminal (which copies our `ENV`). A `JULIA_LOAD_PATH` set to
a single explicit environment drops Julia's default `@` (active project) and `@stdlib` entries, so
inside those children `--project=` / `Pkg.activate` is silently ignored by `using`, and
`Pkg.instantiate` resolves against SpaceStation's internals instead of the user's own project.
(PlutoRunner is loaded into workers through its own boot environment — see `runner/Loader.jl` — so
dropping this pin does **not** affect worker startup; it only stops non-nbpkg notebooks and the
terminal from inheriting our private env.)

Our own `LOAD_PATH` is already materialized in memory, so clearing the *environment variable* here —
once, at startup, before anything is spawned — is a no-op for the running server and lets children
inherit Julia's normal default load path.

Only the app shim's pin is neutralized:
- a `JULIA_LOAD_PATH` the user set themselves keeps the default tokens (`@`, ``, `@stdlib`, …) and
  is left untouched;
- the SSH-remote server is launched with `julia --project=…` (a CLI flag, not an exported env var),
  so it has no pin to clear and this is a no-op there too.
"""
function neutralize_app_load_path_pin!()
    lp = get(ENV, "JULIA_LOAD_PATH", nothing)
    lp === nothing && return
    entries = split(lp, Sys.iswindows() ? ';' : ':')
    # Any default/special token (`@`, empty = "expand default", `@stdlib`, `@v#.#`, `@named`) means
    # the active project is still on the load path — not the bug, and likely user-controlled.
    any(e -> isempty(e) || startswith(e, "@"), entries) && return
    # The Pkg.Apps shim is the only thing that pins a lone app environment (…/environments/apps/…).
    occursin(joinpath("environments", "apps"), lp) || return
    delete!(ENV, "JULIA_LOAD_PATH")
    return
end

"""
    ensure_pluto_collab_installed() -> String | Nothing

Drop the bundled `pluto-collab` CLI next to the `spacestation` app so it's on PATH everywhere
`spacestation` is (external terminals and the integrated terminal alike). Idempotent and
best-effort: only writes when missing or changed, and never throws.
"""
function ensure_pluto_collab_installed()
    isempty(PLUTO_COLLAB_SCRIPT) && return nothing
    try
        bindir = apps_bin_dir()
        isdir(bindir) || mkpath(bindir)
        dest = joinpath(bindir, "pluto-collab")
        if !isfile(dest) || read(dest, String) != PLUTO_COLLAB_SCRIPT
            write(dest, PLUTO_COLLAB_SCRIPT)
            chmod(dest, 0o755)
        end
        return dest
    catch
        return nothing
    end
end

# --- the opt-in AGENTS.md / CLAUDE.md collab section ---

const _AGENTS_BEGIN = "<!-- PLUTOSPACE:BEGIN (managed — this block is regenerated by SpaceStation; edit outside it) -->"
const _AGENTS_END = "<!-- PLUTOSPACE:END -->"

const _AGENTS_BODY = """
## Pluto notebooks (live collaborative sessions)

Notebooks (`*.jl` with Pluto cell markers) in this folder may be OPEN in a live lazy-mode
SpaceStation server. You can work in that same session with your normal tools:

- Edit a notebook `.jl` directly — edits only mark cells **stale**; nothing runs until asked, and
  the human sees the staleness live in their browser.
- `pluto-collab status <nb.jl>` — per-cell state (stale / cold / errored / output).
- `pluto-collab run <nb.jl> --stale` — run exactly what's outdated (blocks; exit 1 on error).
  **Never re-run the whole notebook.**
- `pluto-collab restart <nb.jl>` — restart the kernel and re-run everything. Use ONLY to recover a
  **dead/exited worker** ("Process exited" / `TerminatedWorkerException`); interrupt/run can't revive one.
- Every output is also in `<nb.jl>.pluto-cache.toml` (plain TOML; a deletable cache).
- Cell ids are the UUIDs in `# ╔═╡ <uuid>` markers; keep the `# ╔═╡ Cell order:` block in sync.

`pluto-collab` is on your PATH. Inside a SpaceStation terminal the live server is in
`PLUTOSPACE_PORT` / `PLUTOSPACE_SECRET`, so `pluto-collab` targets it automatically.
"""

_agents_block() = string(_AGENTS_BEGIN, "\n\n", strip(_AGENTS_BODY), "\n\n", _AGENTS_END, "\n")

"Insert or replace the managed SpaceStation block in `content`, preserving everything outside it."
function _upsert_agents_block(content::AbstractString)
    block = _agents_block()
    bi = findfirst(_AGENTS_BEGIN, content)
    ei = findlast(_AGENTS_END, content)
    if bi !== nothing && ei !== nothing && first(bi) <= first(ei)
        pre = rstrip(content[1:prevind(content, first(bi))])
        post = lstrip(content[nextind(content, last(ei)):end])
        return join(filter(!isempty, [pre, rstrip(block), post]), "\n\n") * "\n"
    end
    base = rstrip(content)
    return (isempty(base) ? "" : base * "\n\n") * block
end

"""
    ensure_agents_md(dir; files=("AGENTS.md", "CLAUDE.md"))

Ensure the managed collab section exists in `<dir>/AGENTS.md` (and `CLAUDE.md`). Idempotent: only
the marked block is created/updated; the rest of each file is left untouched. Best-effort.
"""
function ensure_agents_md(dir::AbstractString; files=("AGENTS.md", "CLAUDE.md"))
    isdir(dir) || return
    for name in files
        path = joinpath(dir, name)
        try
            old = isfile(path) ? read(path, String) : ""
            new = _upsert_agents_block(old)
            new == old || write(path, new)
        catch
        end
    end
end

"If opted in (`PLUTOSPACE_AGENTS_MD` truthy) and a workspace is open, refresh its AGENTS.md/CLAUDE.md collab section."
function maybe_write_agents_md(session)
    lowercase(strip(get(ENV, "PLUTOSPACE_AGENTS_MD", ""))) in ("1", "true", "yes", "on") || return
    dir = session.options.server.workspace_folder
    dir === nothing && return
    ensure_agents_md(tamepath(dir))
    return
end
