###
# The agent surface: make the `pluto-collab` CLI PRESENT and DISCOVERABLE so any terminal-based
# coding agent in a SpaceStation session "just works" — no MCP, no plugins, no skills.
#
#  1. ACCESS. `pluto-collab` is a tiny bundled shell script. `Pkg.Apps.add` installs only the
#     `spacestation` Julia entrypoint, so on startup we drop the script next to `spacestation` on PATH
#     (the apps bin dir, which the user already has on PATH to run `spacestation` at all).
#  2. CONNECTION. The integrated terminal exports SPACESTATION_PORT / SPACESTATION_SECRET /
#     SPACESTATION_WORKSPACE, so a tool targets THIS live server with zero discovery (and no
#     ambiguity when several servers run).
#  3. UNDERSTANDING (on by default; opt out with SPACESTATION_AGENTS_MD=0 or --no-agents-md). Drop a
#     managed collab section into the workspace's AGENTS.md and CLAUDE.md — the file conventions
#     coding agents already read. Idempotent (only its own marked block is touched).
###

# The pluto-collab script, embedded at precompile so it ships even when installed purely as an app.
const _PLUTO_COLLAB_PATH = normpath(joinpath(@__DIR__, "..", "bin", "pluto-collab"))
isfile(_PLUTO_COLLAB_PATH) && include_dependency(_PLUTO_COLLAB_PATH)
const PLUTO_COLLAB_SCRIPT = isfile(_PLUTO_COLLAB_PATH) ? read(_PLUTO_COLLAB_PATH, String) : ""

"The directory where `Pkg.Apps` installs app launchers — the same dir that holds the `spacestation` executable, and which the user already has on PATH."
apps_bin_dir() = joinpath(first(DEPOT_PATH), "bin")

"""
    neutralize_app_load_path_pin!()

The `Pkg.Apps` launcher shim for `spacestation` exports

    JULIA_LOAD_PATH=<depot>/environments/apps/SpaceStation

so that `julia -m SpaceStation` boots the server with its *own* dependencies. That is correct for
booting us — but the variable is then inherited by every process the server spawns: notebook
workers (via Malt) and the integrated terminal (which copies our `ENV`). A `JULIA_LOAD_PATH` set to
a single explicit environment drops Julia's default `@` (active project) and `@stdlib` entries, so
inside those children `--project=` / `Pkg.activate` is silently ignored by `using`, and
`Pkg.instantiate` resolves against SpaceStation's internals instead of the user's own project.
(PlutoRunner is loaded into workers through its own boot environment — see `runner/Loader.jl` — so
dropping this pin does **not** affect worker startup; it only stops non-nbpkg notebooks and the
terminal from inheriting our private env.)

Our own `LOAD_PATH` is already materialized in memory, so clearing the *environment variable* here —
once, at startup, before anything is spawned — is a no-op for the running server and lets children
inherit Julia's normal default load path.

Only the app shim's pin is neutralized:
- a `JULIA_LOAD_PATH` the user set themselves keeps the default tokens (`@`, ``, `@stdlib`, …) and
  is left untouched;
- the SSH-remote server is launched with `julia --project=…` (a CLI flag, not an exported env var),
  so it has no pin to clear and this is a no-op there too.
"""
function neutralize_app_load_path_pin!()
    lp = get(ENV, "JULIA_LOAD_PATH", nothing)
    lp === nothing && return
    entries = split(lp, Sys.iswindows() ? ';' : ':')
    # Any default/special token (`@`, empty = "expand default", `@stdlib`, `@v#.#`, `@named`) means
    # the active project is still on the load path — not the bug, and likely user-controlled.
    any(e -> isempty(e) || startswith(e, "@"), entries) && return
    # The Pkg.Apps shim is the only thing that pins a lone app environment (…/environments/apps/…).
    occursin(joinpath("environments", "apps"), lp) || return
    delete!(ENV, "JULIA_LOAD_PATH")
    return
end

"""
    ensure_pluto_collab_installed() -> String | Nothing

Drop the bundled `pluto-collab` CLI next to the `spacestation` app so it's on PATH everywhere
`spacestation` is (external terminals and the integrated terminal alike). Idempotent and
best-effort: only writes when missing or changed, and never throws.
"""
function ensure_pluto_collab_installed()
    isempty(PLUTO_COLLAB_SCRIPT) && return nothing
    try
        bindir = apps_bin_dir()
        isdir(bindir) || mkpath(bindir)
        dest = joinpath(bindir, "pluto-collab")
        if !isfile(dest) || read(dest, String) != PLUTO_COLLAB_SCRIPT
            write(dest, PLUTO_COLLAB_SCRIPT)
            chmod(dest, 0o755)
        end
        return dest
    catch
        return nothing
    end
end

# --- the opt-in AGENTS.md / CLAUDE.md collab section ---

const _AGENTS_BEGIN = "<!-- SPACESTATION:BEGIN (managed — this block is regenerated by SpaceStation; edit outside it) -->"
const _AGENTS_END = "<!-- SPACESTATION:END -->"
const _LEGACY_AGENTS_BEGIN = "<!-- PLUTOSPACE:BEGIN (managed — this block is regenerated by SpaceStation; edit outside it) -->"
const _LEGACY_AGENTS_END = "<!-- PLUTOSPACE:END -->"

const _AGENTS_BODY = """
## Working on Pluto notebooks

**Almost everything you do in a notebook is plain Julia coding you already know how to do** —
writing functions, wrangling data, fixing bugs, making plots, refactoring. A Pluto notebook is just
a **plain Julia file** (`*.jl` starting with `### A Pluto.jl notebook ###`); **edit it with your
normal file tools** (Read/Edit/Write the `.jl` directly). There is no special API for changing a
notebook, and `pluto-collab` (below) is only for *running* your edits, not for making them. Do not
overthink it: it's ordinary Julia in ordinary cells.

The only Pluto-specific parts are a few lightweight conventions wrapped around that Julia code —
learn them so your edits land in the right cell and stay valid:

- **Cells** are delimited by `# ╔═╡ <uuid>` markers. A cell's code runs from its marker to the next
  one. The `<uuid>` is that cell's stable id (a v4 UUID) — used everywhere else in the file.
- **Cell order and fold state** live in the `# ╔═╡ Cell order:` block at the END of the file. It
  lists every cell's UUID in the order it appears in the notebook, each line prefixed by a pipe that
  sets whether that cell's **code (its input) is shown or folded**:
  - `# ╠═<uuid>` → code **shown**
  - `# ╟─<uuid>` → code **hidden / folded** (input collapsed; the normal state for Markdown / prose
    cells, which then display only their rendered output)
- The **Cell order block is authoritative** for display order — not where the `# ╔═╡ <uuid>`
  definition physically sits above.

### How to make common changes (edit the `.jl`)

- **Show or hide a cell's code:** flip that cell's prefix in the Cell order block between `╠═` (show)
  and `╟─` (fold). Do not touch the cell's code — this only changes visibility.
- **Move / reorder a cell:** move its `# ╠═<uuid>` (or `# ╟─<uuid>`) line up or down within the Cell
  order block to the new position. That is what reorders it. (Keeping the `# ╔═╡ <uuid>` definitions
  in the same order is tidy but the Cell order block is what actually decides.)
- **Add a cell:** add a `# ╔═╡ <new-uuid>` block with the code, AND a matching `# ╠═<new-uuid>`
  (or `# ╟─<new-uuid>`) line at the right spot in the Cell order block. Any fresh unique UUID works.
- **Delete a cell:** remove BOTH its `# ╔═╡ <uuid>` code block AND its line in the Cell order block.
- **Cell metadata** (optional) sits on `# ╠═╡ key = value` lines directly after the `# ╔═╡ <uuid>`
  marker — e.g. `disabled = true`, `skip_as_script = true`, `always_stale = true`. A `disabled` cell
  additionally has its code wrapped in `#=╠═╡ … ╠═╡ =#`.

Pluto is **reactive**: what runs, and in what order, follows variable dependencies (topological), not
file order — and each variable/function is defined in exactly **one** cell (duplicate definitions
error; wrap multiple statements in a `begin … end` or `let … end` block). So reordering or folding
cells never changes what executes, only how the notebook reads.

**Bottom line:** write Julia the way you always do. The only extra habits are — keep each definition
in one cell, put multi-statement cells in `begin`/`let` blocks, and when you add, remove, or move a
cell, update the `# ╔═╡ Cell order:` block to match.

### Running your edits (live collaborative session)

Notebooks here may be OPEN in a live lazy-mode SpaceStation server shared with a human. Editing the
`.jl` marks the changed cells **stale** — nothing runs until asked. Their dependents run through
normal Pluto reactivity when those changed cells are explicitly run,
and the human sees the staleness in their browser within ~1s. To apply your changes:

- `pluto-collab status <nb.jl>` — per-cell state (stale / cold / errored / output).
- `pluto-collab run <nb.jl> --stale` — run exactly what's outdated (blocks; exit 1 on error).
  **Never re-run the whole notebook.**
- `pluto-collab restart <nb.jl>` — restart the kernel and re-run everything. Use ONLY to recover a
  **dead/exited worker** ("Process exited" / `TerminatedWorkerException`); interrupt/run can't revive one.
- Every cell's output is also mirrored in `<nb.jl>.pluto-cache.toml` (plain TOML; a deletable cache
  you can read without running anything).

**Live-concurrency guarantees** (server-enforced — parallel agents and a human can work at once):

- Concurrent `run` requests are serialized per notebook; the second recomputes staleness after the
  first finishes, so nothing ever double-executes.
- Editing a cell WHILE it is running is safe: the edit stays pending/stale (outputs are keyed to the
  code that actually ran) — `status` afterwards shows it, `run --stale` applies it.
- A `restart` while another restart is in flight is refused ("already in progress") — poll `status`.
- One caveat: a human's browser edit saves the whole `.jl`; an agent write landing in that same
  instant can be overwritten (the server logs a warning when it happens). Running `status` right
  after your edit confirms the server picked it up.

`pluto-collab` is on your PATH. Inside a SpaceStation terminal the live server is in
`SPACESTATION_PORT` / `SPACESTATION_SECRET`, so `pluto-collab` targets it automatically.

`pluto-collab` needs bash/curl (Unix). On Windows — or anywhere those are missing — use the
identical built-in form `spacestation collab <command> …` (same commands, arguments, and exit
codes; no external dependencies).
"""

_agents_block() = string(_AGENTS_BEGIN, "\n\n", strip(_AGENTS_BODY), "\n\n", _AGENTS_END, "\n")

"Insert or replace the managed SpaceStation block in `content`, preserving everything outside it."
function _upsert_agents_block(content::AbstractString)
    block = _agents_block()
    bi = findfirst(_AGENTS_BEGIN, content)
    ei = findlast(_AGENTS_END, content)
    # Migrate the pre-release PlutoSpace marker in place instead of appending a duplicate block.
    if bi === nothing || ei === nothing
        bi = findfirst(_LEGACY_AGENTS_BEGIN, content)
        ei = findlast(_LEGACY_AGENTS_END, content)
    end
    if bi !== nothing && ei !== nothing && first(bi) <= first(ei)
        pre = rstrip(content[1:prevind(content, first(bi))])
        # Normalize only the separator whitespace around the managed region. Without rstrip here,
        # the unconditional final newline below adds one more blank line on every workspace open.
        post = strip(content[nextind(content, last(ei)):end])
        return join(filter(!isempty, [pre, rstrip(block), post]), "\n\n") * "\n"
    end
    base = rstrip(content)
    return (isempty(base) ? "" : base * "\n\n") * block
end

"""
    ensure_agents_md(dir; files=("AGENTS.md", "CLAUDE.md"))

Ensure the managed collab section exists in `<dir>/AGENTS.md` (and `CLAUDE.md`). Idempotent: only
the marked block is created/updated; the rest of each file is left untouched. Best-effort.
"""
function ensure_agents_md(dir::AbstractString; files=("AGENTS.md", "CLAUDE.md"))
    isdir(dir) || return
    for name in files
        path = joinpath(dir, name)
        try
            old = isfile(path) ? read(path, String) : ""
            new = _upsert_agents_block(old)
            new == old || write(path, new)
        catch
        end
    end
end

"""
    ensure_git_exclude(dir; files)

Keep the seeded files out of `git status` without touching anything shareable: append them to
`.git/info/exclude`, the repo-local, never-committed cousin of `.gitignore`. This is what makes
opt-in seeding polite — the files exist for agents, and git treats them as invisible machine-local
artifacts (issue #73: "Git wants to add and track them as soon as I open a project"). Best-effort:
skipped when `dir` isn't a git repo, when `.git` is a worktree pointer file, or when the entries
are already present (also honors an existing tracked file: exclude only affects untracked paths).
"""
function ensure_git_exclude(dir::AbstractString; files=("AGENTS.md", "CLAUDE.md"))
    gitdir = joinpath(dir, ".git")
    isdir(gitdir) || return  # not a repo, or a worktree pointer file — leave it alone
    path = joinpath(gitdir, "info", "exclude")
    try
        old = isfile(path) ? read(path, String) : ""
        lines = split(old, '\n')
        missing = [name for name in files if !any(l -> strip(l) == name || strip(l) == "/" * name, lines)]
        isempty(missing) && return
        addition = "# SpaceStation agent surface (machine-local; seeded on request)\n" * join(("/" * name for name in missing), "\n") * "\n"
        mkpath(dirname(path))
        write(path, (isempty(old) || endswith(old, "\n") ? old : old * "\n") * addition)
    catch
    end
    return
end

"""
When a folder workspace is open, refresh its AGENTS.md/CLAUDE.md collab section so any coding agent
discovers the pluto-collab workflow.

**Refresh-only by default** (issue #73): a fresh folder is NEVER seeded silently — people who
don't use AI agents shouldn't find generated files in `git status` just for opening a project.
Unset, the managed block is only refreshed where it ALREADY exists (a workspace that opted in
once keeps getting updates). Opt in with `SPACESTATION_AGENTS_MD=1` or `--agents-md` (seeds new
folders too); opt out entirely with `=0` (also `false`/`no`/`off`) or `--no-agents-md`. The
legacy `PLUTOSPACE_AGENTS_MD` name remains accepted. Whenever files are written, they are also
added to `.git/info/exclude` so even opted-in repos keep a clean `git status`. Only runs for a
folder workspace (never for a single-notebook or launcher session — there's no project root to
seed).
"""
function maybe_write_agents_md(session)
    setting = get(ENV, "SPACESTATION_AGENTS_MD", get(ENV, "PLUTOSPACE_AGENTS_MD", ""))
    lowercase(strip(setting)) in ("0", "false", "no", "off") && return
    dir = session.options.server.workspace_folder
    dir === nothing && return
    dir = tamepath(dir)
    force = lowercase(strip(setting)) in ("1", "true", "yes", "on")
    if !force
        # refresh-only: touch nothing unless this workspace already carries the managed block
        has_block = any(("AGENTS.md", "CLAUDE.md")) do name
            path = joinpath(dir, name)
            isfile(path) || return false
            content = try read(path, String) catch; "" end
            occursin(_AGENTS_BEGIN, content) || occursin(_LEGACY_AGENTS_BEGIN, content)
        end
        has_block || return
    end
    ensure_agents_md(dir)
    ensure_git_exclude(dir)
    return
end
