// Regenerates buildinfo.ts from the current checkout before a build. The build tasks restore the
// committed placeholder afterwards (git checkout -- buildinfo.ts).

const here = new URL(".", import.meta.url).pathname
const repo = new URL("..", import.meta.url).pathname

const git = async (...args: string[]) => {
    const out = await new Deno.Command("git", { args: ["-C", repo, ...args], stdout: "piped" }).output()
    if (!out.success) throw new Error(`git ${args.join(" ")} failed`)
    return new TextDecoder().decode(out.stdout).trim()
}

const rev = await git("rev-parse", "HEAD")
const origin = (await git("remote", "get-url", "origin")).replace(/\.git$/, "")

Deno.writeTextFileSync(
    `${here}buildinfo.ts`,
    `// GENERATED by gen_buildinfo.ts — do not edit; the committed default is null/null.
export const project: string | null = ${JSON.stringify(repo)}
export const source: { url: string; rev: string } | null = { url: ${JSON.stringify(origin)}, rev: ${JSON.stringify(rev)} }
`
)
console.log(`buildinfo: project=${repo} source=${origin}#${rev.slice(0, 8)}`)
